version: "3.8"

services:
  # Frontend Server
  frontend:
    depends_on:
      - db
      - passenger-account
      - driver-account
    #   - MS3
    build:
      context: ./client
    container_name: frontend-sever
    ports:
      - 5000:5000
    deploy:
      restart_policy:
        condition: on-failure
  # MySQL Database
  db:
    image: mysql-db:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - mysql-data:/var/lib/mysql
  # Passenger Account Microservice
  passenger-account:
    depends_on:
      - db
    build:
      context: ./microservices/PassengerAccount
    container_name: passenger-ms
    ports:
      - 5001:5001
  # Driver Account Microservice
  driver-account:
    depends_on:
      - db
    build:
      context: ./microservices/DriverAccount
    container_name: driver-ms
    ports:
      - 5002:5002

volumes:
  mysql-data:
